### ISSUE TITLE
Module not found: Error: Can't resolve 'save-file'

### ISSUE THREAD

**Issue by sgehrman** [dy/save-file#14]
just updated to the latest build and I'm getting errors when it runs.

Module not found: Error: Can't resolve 'save-file'

I switched to 2.0.0 and it works fine.

**Comment by pardonmeme** [comment]
@bump

Same problem here

**Comment by dy** [comment]
@pardonmeme what version do you use?

**Comment by m-korkut** [comment]
same problem here

**Comment by dy** [comment]
@m-korkut @pardonmeme @sgehrman
please provide steps to reproduce the bug case.

**Comment by danilomartinelli** [comment]
Same problem here. I have a web project with save-file@1.3.0 and works fine. I just updated to the latest build (2.2.1) and i'm getting the following error: Module not found: Error: Can't resolve 'save-file'. I've tried to use require and import.

**Comment by dy** [comment]
@danilomartinelli do you use webpack or browserify? How did you update to the latest build - via `npm install` or `npm update`? Do you run it in browser or node? What npm/node version do you use?
Your scenario works with my setup well.

**Comment by danilomartinelli** [comment]
> @danilomartinelli do you use webpack or browserify? How did you update to the latest build - via `npm install` or `npm update`? Do you run it in browser or node? What npm/node version do you use?
> Your scenario works with my setup well.

I use webpack@4.29.0 and i updated  to the lastest build via npm install (I use npm-check). I run it in browser. I use node v10.15.0 and npm v6.4.1

**Comment by danilomartinelli** [comment]
Any update?

**Comment by kamranayub** [comment]
Brand new user and same issue, doing a React (Gatsby) app and used npm install method. I believe they're using webpack + babel. Using:

```js
import save from 'save-file'
```

And get:

    Module not found: Error: Can't resolve 'save-file'

**Comment by dy** [comment]
save-file@2.3.0 should have it fixed
